# SPDX-FileCopyrightText: Contributors to NPAP
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: '\.svg$'
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: '\.svg$'
      - id: trailing-whitespace
        exclude: '\.svg$'
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        args: ["--maxkb=30000"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: '\.svg$'
        additional_dependencies:
          - tomli
