name: npap_env
channels:
  - defaults
  - conda-forge
dependencies:
  - hdbscan
  - networkx
  - numpy
  - pandas
  - plotly
  - pip
  - scikit-learn
  - scikit-learn-extra
  - pip:
      - -e .
      - kaleido
